### ISSUE TITLE
Ime repozitorijuma

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp2019/GenFunCpp#2]
Drage kolege,

Promenio sam ime repozitorijuma (sada se koristi pravo ime) - cisto da znate ukoliko ste negde koristili linkove ka repozitorijumu. Dao sam ime Compound-Units, ako zelite neko drugo, samo odgovorite ovde i promenicu. U protivnom samo zatvorite issue.

**Comment by Gillgalard** [comment]
Hvala za obavestenje.
